### ISSUE TITLE
make your membership public?

### ISSUE THREAD

**Issue by jennybc** [forwards/row#1]
Hi @lawremi @dicook @Ironholds @hturner 

I was fiddling with other aspects of my GitHub profile and noticed that my membership in the Women in R Organization was not public. I toggled it to public.

All other things being equal, it seems like we all should. What does this do? This means when someone looks at your GitHub profile, this Organization will show up. And when someone looks at this Organization, you profile will show up.

How do you toggle?

Go here:

https://github.com/orgs/forwards/people

and click on the "Private" lock icon to access a drop-down menu, where you can opt for Public.

Are the rest of our task force not on GitHub and that's why only we 5 are members?

**Comment by hturner** [comment]
Thanks for this suggestion Jenny, good idea.
 
I will check with those that aren't mentioned as to whether they are
on Github.
 
 
On Thu, May 12, 2016, at 03:04 AM, Jennifer (Jenny) Bryan wrote:
> Hi @lawremi[1] @dicook[2] @Ironholds[3] @hturner[4]
> I was fiddling with other aspects of my GitHub profile and noticed
> that my membership in the Women in R Organization was not public. I
> toggled it to public.
> All other things being equal, it seems like we all should. What does
> this do? This means when someone looks at your GitHub profile, this
> Organization will show up. And when someone looks at this
> Organization, you profile will show up.
> How do you toggle?
> Go here:
> https://github.com/orgs/forwards/people
> and click on the "Private" lock icon to access a drop-down menu, where
> you can opt for Public.
> Are the rest of our task force not on GitHub and that's why only we 5
> are members?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[5]
>
 

Links:

  1. https://github.com/lawremi
  2. https://github.com/dicook
  3. https://github.com/Ironholds
  4. https://github.com/hturner
  5. https://github.com/forwards/row/issues/1

**Comment by jennybc** [comment]
@lawremi and @dicook look like they belong to the "hadley organization", due to the avatar for [ggobi](https://github.com/ggobi) 😏.

**Comment by dicook** [comment]
I just *fixed* it! If that’s the right word. It was a little strange that it was Hadley’s picture but I didn’t think to mess with it before,

Also changed my forwards membership to be public.

Thx for these,

cheers,
Di

> On May 13, 2016, at 12:24 AM, Jennifer (Jenny) Bryan <notifications@github.com> wrote:
> 
> @lawremi and @dicook look like they belong to the "hadley organization", due to the avatar for ggobi 😏.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by jennybc** [comment]
I guess 3 for 4 ain't bad,

**Comment by hturner** [comment]
@DragonflyStats @julierennes since you joined the Github organisation after Jenny opened this issue, could you take a look and consider: [make your membership public?](https://github.com/forwards/row/issues/1)
